version: "3.8"
name: link-generator-backend
services:
  link-generator:
    container_name: link-generator-backend
    build: "."
    restart: always
    ports:
      - "4000:4000"
    environment:
      - REDIS_ADDR=redis-server:6379
    depends_on:
      - redis

  redis:
    container_name: redis-server
    image: "redis:latest"
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    name: redis-data